/**
 * Post-build script: scans the `out/` directory and generates a service worker
 * with a full precache manifest so the PWA works offline from the first visit.
 */

import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const OUT_DIR = join(process.cwd(), "out");
const SW_OUTPUT = join(OUT_DIR, "sw.js");

// Recursively collect all files in a directory
async function collectFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(fullPath)));
    } else {
      files.push(fullPath);
    }
  }

  return files;
}

// Generate a short content hash for cache-busting
function hashFile(filePath) {
  const content = readFileSync(filePath);
  return createHash("md5").update(content).digest("hex").slice(0, 8);
}

async function main() {
  const allFiles = await collectFiles(OUT_DIR);

  // Convert to URL paths relative to out/
  const precacheEntries = [];

  for (const file of allFiles) {
    const relPath = relative(OUT_DIR, file).replace(/\\/g, "/");

    // Skip the SW itself and source maps
    if (relPath === "sw.js" || relPath.endsWith(".map")) continue;

    const url = "/" + relPath;
    const hash = hashFile(file);
    precacheEntries.push({ url, revision: hash });
  }

  // Also add "/" explicitly (maps to /index.html)
  const indexEntry = precacheEntries.find((e) => e.url === "/index.html");
  if (indexEntry) {
    precacheEntries.push({ url: "/", revision: indexEntry.revision });
  }

  // Generate a cache version based on current timestamp
  const cacheVersion = `icongen-v${Date.now()}`;

  const swContent = `// Auto-generated by scripts/generate-sw.mjs — do not edit manually
const CACHE_NAME = "${cacheVersion}";

const PRECACHE_ENTRIES = ${JSON.stringify(precacheEntries, null, 2)};

const PRECACHE_URLS = PRECACHE_ENTRIES.map((e) => e.url);

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  // Network-first for navigation requests (HTML pages)
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          const responseToCache = response.clone();
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, responseToCache);
          });
          return response;
        })
        .catch(() => caches.match(event.request))
    );
    return;
  }

  // Cache-first for all other assets (JS, CSS, images, mocks, etc.)
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;

      return fetch(event.request).then((response) => {
        if (
          !response ||
          response.status !== 200 ||
          response.type !== "basic"
        ) {
          return response;
        }

        const responseToCache = response.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });

        return response;
      });
    })
  );
});
`;

  await writeFile(SW_OUTPUT, swContent, "utf-8");
  console.log(
    `[generate-sw] Wrote ${SW_OUTPUT} with ${precacheEntries.length} precache entries (cache: ${cacheVersion})`
  );
}

main().catch((err) => {
  console.error("[generate-sw] Failed:", err);
  process.exit(1);
});
